### ISSUE TITLE
Investigate whether network connection issues are causing download failures (and whether thats affecting failure rate)

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry-sdk#1185]
If the daemon is not able to download content, calls to `get` should error.

**Comment by kauffj** [comment]
Level 1 is that the `connection_status` value returned by the `status` command update.

Level 2 is for the daemon to be able to issue calls to the clients, rather than clients only polling the daemon. I could only find #854 as documenting this.

But if `status` updates and an application can say "call me when the output of `status` changes", then we have the functionality we need app side.

Even without the second feature, we can busy-poll to detect connection status changes.

**Comment by eukreign** [comment]
@jackrobison what's the status of this in the new async DHT / blob exchange?

**Comment by alyssaoc** [comment]
@jackrobison this is related to analytics
