### ISSUE TITLE
channel_export/channel_import

### ISSUE THREAD

**Issue by alyssaoc** [lbryio/lbry-sdk#1409]

**Comment by tzarebczan** [comment]
These are not critical, but since these 2 commands are not currently working, we should consider fixing them sooner than later.

**Comment by tzarebczan** [comment]
Users should be able to export their certificate and public key in a data format that can later be imported by another user. This other user should be able to sign claims with that certificate. I believe the public key needs to be imported for the channel as a 2nd account (maybe this is no longer a requirement with the recent cert / pubkey changes? ) 

Nice to have: if a channel certificate is invalidated (you'd know from the public key), it should not be allowed to sign the content and show an appropriate error message.

**Comment by tzarebczan** [comment]
The basics of this was completed, but a user who imports a channel certificate will not see it when they run `channel list`. Since this is a special use case for accounts, this account should be included as if it were the default account if account commands are passed without an account id. Something similar to https://github.com/lbryio/lbry/issues/2004 should happen if the user doesn't have the channel itself, and only the signing key.  There should be some way to tell it was imported.

**Comment by lyoshenka** [comment]
does #2220 solve this?

**Comment by tzarebczan** [comment]
It does, yes.

**Comment by tzarebczan** [comment]
This now works as expected.
