### ISSUE TITLE
comment hide/moderate API (and comment list changes)

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-sdk#2369]
To support moderation on claims owned by a channel, a new API will be created to allow the channel owner to mark comment ids as moderated. These will be marked as such on the comment server. For the longer term blockchain solution, this would require the channel owner to create a transaction to hide them (can probably do these in batches). Their other option is to disable comments so they aren't shown in the GUI. 

### New:
comment hide/moderate (which one is better longer term?):

Param: comment ids (one or more, array)
Sends signature to comment server for validation

### Updates:
comment list 
- [ ] should return how many moderated comments there are in its response. This will allow the app to show a warning / allow users to see the comments if they wanted. 

- [ ] do not return moderated comments by default 

- [ ] parameter to return moderated comments only / along with other comments (this would be good for threading/replies to show where the moderated comments are).

**Comment by osilkin98** [comment]
I'm not completely sure about this. As described, this would cause a bit of discrepancies in the API.
 
### Naming the Function `comment_moderate`
Referring to the comments as being 'moderated' would imply that this is an official process in which LBRY Inc. or some other entity would be in charge of reviewing flagged content. Since the comments are just being marked as 'hidden' by the channel owner, this would be misleading.

### Including the Moderated Comment Count In The Response
This would mean adding a new field `moderated_count` into the paginated response, and thus having a function that returns a field that isn't going to be there 100% of the time.  

This also implies the default functionality is including non-moderated comments. What happens if I ask only for the moderated comments; would `moderated_count` disappear, or be set to 0?  

It would also be weird for the API to have this field exist in this one specific function, but not for others. Thus creating an inconsistent API. 


### Removing Hidden Comments From `comment_list` by Default

Each comment being returned will have a boolean field `is_hidden`. If I did `comment list "Eiffel Tower"` I would expect to get a list of all the comments on the Eiffel Tower. I'm expecting this to represent **all** the comments being returned. 

If I want to filter out the comments being hidden, I would do `comment list --filter-hidden "Eiffel Tower"`. 

Since the original list provides all the comments and their attributes, I can do the filtering myself. The flag just simplifies the process. 


## Proposed Changes

### Create new `comment_hide` function
This function would be in charge of allowing the user to set comments as hidden on their claim. The function should take a `claim_id` and a list of `comment_id`s placed under the given `claim_id`  

### Add `--filter_hidden` flag to `comment_list`   
This flag should do as the name implies, and filter hidden comments. It should be off by default.

**Comment by osilkin98** [comment]
For the `comment_hide` function, there should be a flag `--unhide` defaulted to `false`. This way, there is a clear understanding what's being done to all the `comment_ids`, so duplicate entries don't have their flag flipped.

**Comment by tzarebczan** [comment]
1) comment hide is fine then 

2) function that returns a field that isn't going to be there 100% of the time. - return it all the time with 0, or false.

3) This also implies the default functionality is including non-moderated comments. - no, it doesn't, it just tells the user running it there are some moderated ones so they know if they need to run with the hidden flag to see them. 

4) What happens if I ask only for the moderated comments; would moderated_count disappear, or be set to 0? - it would return the same number, or true. 

5) comment list --filter-hidden "Eiffel Tower". fine as long as the api returns whether or not they were filtered (see above). The app would use this by default. 

6) Why do I need a claim id if I already know what comment I'm hiding - the server should figure out if this is allowed or not based on the claim id of the comment / if I'm the channel owner of that claim id. What if we allow a comments console where I may want to hide 10 comments across 5 claim ids? 

7) There needs to be a way to return all moderated comments only, not along with others. This would be the case of a user wanting to see them anyway. 

8) don't understand the whole unhide concept - once something is hidden, it can't be unhidden.  Comment hide already tells you it's hiding it. 

@eukreign can comment on any other specifics.

**Comment by eukreign** [comment]
If it works for the app team then I think this is fine. I expect we'll review the API in much greater detail when we decide to move to a blockchain solution.

**Comment by osilkin98** [comment]
To point 2; this is fine, but it shouldn't go with the rest of the paginated info. 
E.g, you're asking for this:
```
{
  "items": [...],  # information about the raw content, appears everywhere in API
  "page_size": 10,
  "total_items": 1,
  "total_pages": 1
  "hidden_items": 0  # Information about a subset of the content, appears in this one function 
}
```

> comment list --filter-hidden "Eiffel Tower". fine as long as the api returns whether or not they were filtered (see above). The app would use this by default.

If the default functionality is to return all comments, then there's no need to specify whether or not a filter was applied to it in the output, this is already known by the original call.

> Why do I need a claim id if I already know what comment I'm hiding - the server should figure out if this is allowed or not based on the claim id of the comment / if I'm the channel owner of that claim id. What if we allow a comments console where I may want to hide 10 comments across 5 claim ids?

Because the call to the server itself needs to be signed by the channel that owns the content. If the server gets a list of just random comment IDs, then it's unknown if they're on the same claim, or if the caller even owns the claim. This is information that is needed which the SDK can easily obtain before making the call to the server.


> There needs to be a way to return all moderated comments only, not along with others. This would be the case of a user wanting to see them anyway.

Exactly, which is exactly how you would use filters. To get only the non-hidden functions you would do `--filter-hidden=hide`, and to get only the hidden you would do `--filter-hidden=show`.


> don't understand the whole unhide concept - once something is hidden, it can't be unhidden. Comment hide already tells you it's hiding it.

What if you didn't mean to hide it and want to revert it?

**Comment by tzarebczan** [comment]
1) That's exactly what we want, but it doesn't have to do a count...just return "has_hidden_comments" true/false

2) " then there's no need to specify whether or not a filter was applied to it in the output, this is already known by the original call." - goes with #1 - the app needs to know if there are ANY hidden comments from a single call. 

3) I never said it shouldn't send the signed data for the comment ids...yes, of course, this needs to happen. It's up to the server to decide if it's a valid request because the server also knows if the channel requesting them has permission to do so based on the comment id alone. If passed a comment id that's not valid, disregard it. Passing claim id is not necessary, just like it's not for comment delete. 

4) filter-hidden=hide/show don't make sense to me. Try to stick to one functionality to parameter, or don't use the term filter-hidden if it's going to actually show them. 

5) let's not worry about unhiding for now.

**Comment by osilkin98** [comment]
For #3, the `delete` function is already having to make 2 requests to the server, the first being to figure out which channel the comment id is linked to. Doing it the proposed way would require having to do the same but with even more redundant information and queries that could just be fixed by providing the `claim_id`.

**Comment by osilkin98** [comment]
It seems like a good signature for `comment_hide` would be:
```py
Usage:
     comment_hide  <comment_ids>...

Returns: 
    (list) containing the comment_ids successfully hidden
```

**Comment by lyoshenka** [comment]
closing since comments are outside sdk
