### ISSUE TITLE
claim search results with duplicate reposts (consolidating by default)

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-sdk#2812]
By default, claim search should handle duplicate results (squash) of reposted claim ids and return whichever record would otherwise come first.  The problem becomes when multiple channels repost the same content, app users will have duplicate displays of the same content. 

For example, if you are sorting by effective amount, show the repost record with the highest effective amount. If you are sorting by release time, show the earliest record. If you are sorting by trending, show the record with the highest trending value. 

It should also be possible to add a flag that would return the full result. 

Eventually, it would also be nice to return multiple channels in the single result that combine into the squashed result so that the app can show "this was reposted by x, y, z and...". 

Another scenario to consider is a single channel that reposts the same claim under multiple URLs - we'd only want to see this once - probably with the same rules as above.

**Comment by shyba** [comment]
the PR for limiting is on #3301 with status being updated there.
> It should also be possible to add a flag that would return the full result.

I did it following the pattern from `limit_claims_per_channel`, so it preserves order but acts globally instead of per page. Currently it is a flag, but we can make some number the default if desired.

> Eventually, it would also be nice to return multiple channels in the single result that combine into the squashed result so that the app can show "this was reposted by x, y, z and...".

the hub already knows how many times it was reposted, but doesn't return that on any API yet. I think is is a candidate for another issue maybe? Also, telling who reposted each claim while preserving order requires a more convoluted query, but can be done too.. I think it deserves its own issue so we can clarify how many to return and which criteria to use?

note if we create an issue: picking X channels who reposted can probably be done on index time, so we remove query penalties.

> Another scenario to consider is a single channel that reposts the same claim under multiple URLs - we'd only want to see this once - probably with the same rules as above.

I believe this is covered but will add this to the integration tests.

**Comment by tzarebczan** [comment]
This will be available in the next release on be deployed on web apis asap.
