### ISSUE TITLE
Output one-line error messages

### ISSUE THREAD

**Issue by andybeletsky** [lbryio/lbry-sdk#3385]
SDK needs to output one-line error messages instead of full traces by default.

**Comment by belikor** [comment]
I don't know the SDK code perfectly but there are many layers where errors are raised and handled. Often the code will work even if it's not trapped properly because an upper layer will handle it, and will just print the trace.

For example, in #3361 a simple fix makes the trace go away, and the exception is properly raised and handled.

On the other hand, in #3364 a simple fix was rejected because the main developers think it should be handled in a lower level.

**Comment by lyoshenka** [comment]
fixed in #3399

**Comment by andybeletsky** [comment]
The traces seem to be gone but we may have reduced the verbosity too much. I'm seeing this in the logs now, without any additional context.

<img width="828" alt="Screen Shot 2021-09-04 at 02 36 57" src="https://user-images.githubusercontent.com/1574292/132057784-2c79d0a8-3575-41d9-9cf3-782f2d5b41a9.png">

**Comment by lyoshenka** [comment]
lets keep this closed. i opened a new issue: #3419
