### ISSUE TITLE
Suggesting that...

### ISSUE THREAD

**Issue by Xyncgas** [lbryio/lbry-sdk#3416]
LBRY protocol needs tutorials and (more) explainations.
You guys need to show people how to put something inside lbry.
Tell people that this can be the storage solution for their applications and reduce hosting cost they are going to love it.

**Comment by Xyncgas** [comment]
I was a teenager when I saw lbry, I thought you were definitely going to do something like this.
Now all the libraries from microsoft tells you how to build it and run it with a single command, for example creating your first hello world in razor page through asp.net, I am still not seeing how I can use the lbry protocol and I think it would be nice if it were to be made more clearer.

**Comment by belikor** [comment]
First of all. Dude, use a better title for this issue. Generic titles are completely useless because you can't tell what it is about with a quick glance, and you can't reference them later on.

Second. The code is open; a true programmer that knows what he is doing can just go inside the code, read the documentation, test things, and figure out things without needing to be hand held all the time. Obviously it's hard but this is the way in free software; if you are committed to the cause you can do it.

In fact you can write this type of documentation yourself, this is one of the best things newcomers can do; they can help by documenting things that seem poorly documented. You can't expect a software project with limited resources to have extremely detailed documentation for everything.

> Tell people that this can be the storage solution for their applications and reduce hosting cost

And exactly what does this mean? The LBRY Inc. company isn't going to store everything for you. The BitTorrent system works in essentially the same way. Have you told everybody to use BitTorrent to save on hosting costs as well?

> I am still not seeing how I can use the lbry protocol

Just like BitTorrent.

**Comment by Xyncgas** [comment]
Ok. I need to talk to your manager.

**Comment by Xyncgas** [comment]
you're right. I think lbry needs to go one step further in the direction I've mentioned, maybe not exact, but that's my opinion that it would help lbry to step up to the next level. Ok so if your resource is limited, that justified that you are not doing this while microsoft has made their products so easy to use, but what about this open letter from lbry saying you guys are trying to get to the next level and has expressed signals for community feedbacks? that's why I need to talk to your manager.

**Comment by cristi-zz** [comment]
Hi @Xyncgas ! The odysee.com is a perfect self documented "interface" to lbry sdk. Yeah, there is a gap between GUI interface and doing all from command line, but, tbh, (1) is not that wide, if one wants to scripting, one already is willing to get their hands dirty of coding and (2) one needs a speck of learning about blockchain, DHT, and overall architecture of LBRY to know what is possible and what is not. My 2 cents . . .

**Comment by Xyncgas** [comment]
Thanks.
